Repository beam-community/jsonapi, pull requests merged in 2019-02, with the labels that each got.

#173 Typespec Tweaks
  lib/jsonapi/config.ex
  lib/jsonapi/page.ex
Labels: enhancement

#172 Remove `Config.required_fields`
  lib/jsonapi/config.ex
Labels: enhancement, question

#177 Credo fixes to comply with --strict option
  .travis.yml
  lib/jsonapi.ex
  lib/jsonapi/serializer.ex
Labels: enhancement

#176 Issue175
  lib/jsonapi/error_view.ex
  lib/jsonapi/plugs/format_required.ex
  test/jsonapi/plugs/format_required_test.exs
Labels: enhancement

#180 Report on missing data[type] as such
  lib/jsonapi/error_view.ex
  lib/jsonapi/plugs/format_required.ex
  test/jsonapi/plugs/format_required_test.exs
Labels: bug

#178 Globally Configurable Namespace
  README.md
  lib/jsonapi/view.ex
  test/jsonapi/view_test.exs
Labels: enhancement

#181 Move Serializer Test
  test/jsonapi/serializer_test.exs
Labels: enhancement

#182 Replace reference to literal `field_name/2`
  lib/jsonapi/view.ex
Labels: enhancement

#171 Fully Support Sparse Fieldsets
  README.md
  lib/jsonapi/plugs/query_parser.ex
  lib/jsonapi/view.ex
  test/jsonapi/plugs/query_parser_test.exs
  test/jsonapi/view_test.exs
  test/jsonapi_test.exs
Labels: enhancement
